<%

# This code will try to connect to the first database it finds (either mysql or postgres)
# This is just an example application so this is ok. Don't try to use this
# code in production if you are planning to bound more than one databases.
services = JSON.parse(ENV["VCAP_SERVICES"])
db_service = services.values.flatten.find do |service_attrs|
  ['mysql','postgres'].include?(service_attrs["label"])
end

conf={
  username: db_service['credentials']['user'],
  password: db_service['credentials']['password'],
  database: db_service['credentials']['database'],
  host: db_service['credentials']['host'],
  port: db_service['credentials']['port'].to_i
}

case db_service["label"]
when 'mysql'
  conf[:adapter] = 'mysql2'
  conf[:encoding] = 'utf8'
when 'postgres'
  conf[:adapter] = 'postgresql'
  conf[:encoding] = 'unicode'
end

puts conf
%>

default: &default
  adapter: <%= conf[:adapter] %>
  encoding: <%= conf[:encoding] %>
  database: <%= conf[:database] %>
  username: <%= conf[:username] %>
  password: <%= conf[:password] %>
  host: <%= conf[:host] %>
  port: <%= conf[:port] %>
  pool: 5

development:
  <<: *default

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default

production:
  <<: *default
